{
  lib,
  rustPlatform,
  pkg-config,
  sources,
}:
let
  version = lib.removePrefix "v" sources.mdr-rs.version;
in
rustPlatform.buildRustPackage {
  pname = "mdr";
  inherit version;
  src = sources.mdr-rs.src;

  # Upstream does not commit a Cargo.lock (it's .gitignore'd, even in the
  # release tag tree -- confirmed absent from v0.3.2; upstream's own
  # flake.nix has this same latent bug). This Cargo.lock is generated by us
  # (`cargo generate-lockfile` against the v0.3.2 source) and committed
  # alongside this file -- it is NOT derived from sources.mdr-rs.src.
  # Regenerate it whenever this package's pinned version bumps and the build
  # starts failing: check out the new tag, run `cargo generate-lockfile`,
  # commit the result here (and regenerate add-cargo-lock.patch to match, see
  # below). Unlike gomu/pint/glowm's mechanical vendorHash bump, this step
  # can't be automated by the nightly update-locks.sh run -- a
  # dependency-changing version bump surfaces as a failing CI check on the
  # auto-opened PR instead of silently going stale, which is the intended
  # fallback.
  cargoLock.lockFile = ./Cargo.lock;

  # rustPlatform's cargoSetupPostPatchHook diffs the source's own Cargo.lock
  # against the vendor dir's and fails outright if the source has none at
  # all (confirmed: build error "Missing Cargo.lock from src... Hint: You
  # can use the cargoPatches attribute to add a Cargo.lock manually to the
  # build" -- that hint is nixpkgs' own documented workaround for exactly
  # this upstream-ships-no-lockfile case). This patch inserts a byte-identical
  # copy of ./Cargo.lock into the unpacked source before that check runs, so
  # the diff is empty and the check passes.
  cargoPatches = [ ./add-cargo-lock.patch ];

  nativeBuildInputs = [ pkg-config ];

  # No buildInputs needed: `darwin.apple_sdk` was removed from nixpkgs
  # (throws in this repo's pinned nixpkgs-26.05-darwin); nixpkgs' own
  # migration guidance is to drop such references outright, since the
  # default SDK already provides WebKit/AppKit/CoreServices for the
  # webview/egui backends.
  #
  # Darwin-only for now: upstream's own flake also lists Linux buildInputs
  # (gtk3, webkitgtk_4_1, libxdo, libGL) plus wrapGAppsHook, but at this
  # repo's pinned nixpkgs rev `libxdo` does not exist as an attribute at all
  # (verified against github:NixOS/nixpkgs/33da5f36e599b50aa7dbbfacb718254423b18354
  # -- likely present only in a newer nixpkgs than this stable pin). Rather
  # than guess at a replacement for a platform nobody here uses yet, this
  # package is Darwin-only until someone actually wants it on Linux and can
  # resolve the current dependency names against whatever nixpkgs rev is
  # pinned then.

  # Skip upstream's test suite: the default feature set builds a GUI/webview
  # toolkit whose tests expect a display; the nvfetcher-pinned SHA plus the
  # committed Cargo.lock are the integrity proof, same rationale as
  # pint/glowm/gomu's doCheck = false.
  doCheck = false;

  meta = {
    description = "A lightweight Markdown viewer with Mermaid diagram support and live reload";
    homepage = "https://github.com/CleverCloud/mdr";
    license = lib.licenses.mit;
    mainProgram = "mdr";
    platforms = lib.platforms.darwin;
  };
}
