# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bat-gherkin-syntax = {
    pname = "bat-gherkin-syntax";
    version = "ec3fae90209136a89a5027f61167e04790c83382";
    src = fetchFromGitHub {
      owner = "keith-hall";
      repo = "SublimeGherkinSyntax";
      rev = "ec3fae90209136a89a5027f61167e04790c83382";
      fetchSubmodules = false;
      sha256 = "sha256-yYIMfzAiKdQsl3OPSevENsrs4TkNe+eVVPSRbtHagNY=";
    };
    date = "2024-10-12";
  };
  bunny = {
    pname = "bunny";
    version = "71b14a3d624572f4884354c2e218296e9ece07cc";
    src = fetchFromGitHub {
      owner = "stelcodes";
      repo = "bunny.yazi";
      rev = "71b14a3d624572f4884354c2e218296e9ece07cc";
      fetchSubmodules = false;
      sha256 = "sha256-uQO0C00yOFPWq8KEO/kEZM6tFZRc9SiXfgN7kzlwDeA=";
    };
    date = "2026-03-08";
  };
  cmux = {
    pname = "cmux";
    version = "0.64.22";
    src = fetchurl {
      url = "https://github.com/manaflow-ai/cmux/releases/download/v0.64.22/cmux-macos.dmg";
      sha256 = "sha256-/RSNujUZ/n0wiEQInOTQYrF3ObpkViPwWPZ6ZHmM6iU=";
    };
  };
  eclipse-java = {
    pname = "eclipse-java";
    version = "2026-06-R";
    src = fetchurl {
      url = "https://download.eclipse.org/technology/epp/downloads/release/2026-06/R/eclipse-java-2026-06-R-macosx-cocoa-aarch64.dmg";
      sha256 = "sha256-w3B7LiarR9eZglhCVBqveXt/L9TAl1TJiSbl14kT5Ik=";
    };
  };
  gh-stack = {
    pname = "gh-stack";
    version = "v0.1.0";
    src = fetchFromGitHub {
      owner = "github";
      repo = "gh-stack";
      rev = "v0.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-48JkOeqbvHlCZ2u3LnwJymw55xMQWLTPJLDbV44clGI=";
    };
  };
  glowm = {
    pname = "glowm";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "atani";
      repo = "glowm";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-kyylQrn2OROQe+taGEw0L7q5Y6HW+UqDcA46DOgeOYI=";
    };
  };
  gomu = {
    pname = "gomu";
    version = "v0.2.1";
    src = fetchFromGitHub {
      owner = "sivchari";
      repo = "gomu";
      rev = "v0.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-MYYtqv0q6ExyETxrUMW5KTs87mahik+0RwO9xV3h82I=";
    };
  };
  icons-brew = {
    pname = "icons-brew";
    version = "e524eaccce065103774148fcb445621dd5bdc17a";
    src = fetchFromGitHub {
      owner = "lpnh";
      repo = "icons-brew.yazi";
      rev = "e524eaccce065103774148fcb445621dd5bdc17a";
      fetchSubmodules = false;
      sha256 = "sha256-wBpjAHikC06uJEbjaQQffCZq1QjMDJ2XSm8AJcOfmLE=";
    };
    date = "2026-07-11";
  };
  logseq = {
    pname = "logseq";
    version = "2.0.1";
    src = fetchurl {
      url = "https://github.com/logseq/logseq/releases/download/2.0.1/Logseq-darwin-arm64-2.0.1.dmg";
      sha256 = "sha256-t2ryU4T4qqC6Mi+LVSOupxLZdQ2fPnnKxV3Hg3lkOc0=";
    };
  };
  lombok = {
    pname = "lombok";
    version = "1.18.48";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.48/lombok-1.18.48.jar";
      sha256 = "sha256-hUd6RlXrssB0qQmc+3Sb5FREn+5WTUKCYQ3xuF98UIs=";
    };
  };
  mdr-rs = {
    pname = "mdr-rs";
    version = "v0.3.2";
    src = fetchFromGitHub {
      owner = "CleverCloud";
      repo = "mdr";
      rev = "v0.3.2";
      fetchSubmodules = false;
      sha256 = "sha256-Cf07bCdCa9bRO1TiNQPu78aDRE3BQR3YstPr3G+RZUE=";
    };
  };
  pint = {
    pname = "pint";
    version = "v0.87.0";
    src = fetchFromGitHub {
      owner = "cloudflare";
      repo = "pint";
      rev = "v0.87.0";
      fetchSubmodules = false;
      sha256 = "sha256-gQosR2LovEEw0AOzIf91AJAL2cMvygMEsYGszvSYFps=";
    };
  };
  tmux-mouse-swipe = {
    pname = "tmux-mouse-swipe";
    version = "6d7394923d2c9bda653515e3bd658490ba511c2a";
    src = fetchFromGitHub {
      owner = "jaclu";
      repo = "tmux-mouse-swipe";
      rev = "6d7394923d2c9bda653515e3bd658490ba511c2a";
      fetchSubmodules = false;
      sha256 = "sha256-vLEcaQS/zgcJ5t57MsiY7hMS648l+zwrS1r1v0KZs/4=";
    };
    date = "2026-08-01";
  };
  tmux-nerd-font-window-name = {
    pname = "tmux-nerd-font-window-name";
    version = "f464c59e459d91d7b0db702e2f436475c4e9bf4f";
    src = fetchFromGitHub {
      owner = "joshmedeski";
      repo = "tmux-nerd-font-window-name";
      rev = "f464c59e459d91d7b0db702e2f436475c4e9bf4f";
      fetchSubmodules = false;
      sha256 = "sha256-fsfhOmmAVwp/+kUcxi6ZvEfoNL1twJie8MhgNk/+UwE=";
    };
    date = "2026-08-20";
  };
  tmux-open-nvim = {
    pname = "tmux-open-nvim";
    version = "d140ac66e24f1cd26b68638da01a82717a1921bd";
    src = fetchFromGitHub {
      owner = "trevarj";
      repo = "tmux-open-nvim";
      rev = "d140ac66e24f1cd26b68638da01a82717a1921bd";
      fetchSubmodules = false;
      sha256 = "sha256-lftDhRERenGVDTWFP1o/bfZIk0RsHh2PxoYY8j8/9CQ=";
    };
    date = "2026-04-20";
  };
}
