# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  bat-gherkin-syntax = {
    pname = "bat-gherkin-syntax";
    version = "ec3fae90209136a89a5027f61167e04790c83382";
    src = fetchFromGitHub {
      owner = "keith-hall";
      repo = "SublimeGherkinSyntax";
      rev = "ec3fae90209136a89a5027f61167e04790c83382";
      fetchSubmodules = false;
      sha256 = "sha256-yYIMfzAiKdQsl3OPSevENsrs4TkNe+eVVPSRbtHagNY=";
    };
    date = "2024-10-12";
  };
  bunny = {
    pname = "bunny";
    version = "71b14a3d624572f4884354c2e218296e9ece07cc";
    src = fetchFromGitHub {
      owner = "stelcodes";
      repo = "bunny.yazi";
      rev = "71b14a3d624572f4884354c2e218296e9ece07cc";
      fetchSubmodules = false;
      sha256 = "sha256-uQO0C00yOFPWq8KEO/kEZM6tFZRc9SiXfgN7kzlwDeA=";
    };
    date = "2026-03-08";
  };
  cmux = {
    pname = "cmux";
    version = "0.64.19";
    src = fetchurl {
      url = "https://github.com/manaflow-ai/cmux/releases/download/v0.64.19/cmux-macos.dmg";
      sha256 = "sha256-npYbupFZ8tgg+OHX9YpTLRmth1i7dTZaV/183Jp8/PQ=";
    };
  };
  eclipse-java = {
    pname = "eclipse-java";
    version = "2026-06-R";
    src = fetchurl {
      url = "https://download.eclipse.org/technology/epp/downloads/release/2026-06/R/eclipse-java-2026-06-R-macosx-cocoa-aarch64.dmg";
      sha256 = "sha256-w3B7LiarR9eZglhCVBqveXt/L9TAl1TJiSbl14kT5Ik=";
    };
  };
  glowm = {
    pname = "glowm";
    version = "v0.4.0";
    src = fetchFromGitHub {
      owner = "atani";
      repo = "glowm";
      rev = "v0.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-kyylQrn2OROQe+taGEw0L7q5Y6HW+UqDcA46DOgeOYI=";
    };
  };
  icons-brew = {
    pname = "icons-brew";
    version = "e524eaccce065103774148fcb445621dd5bdc17a";
    src = fetchFromGitHub {
      owner = "lpnh";
      repo = "icons-brew.yazi";
      rev = "e524eaccce065103774148fcb445621dd5bdc17a";
      fetchSubmodules = false;
      sha256 = "sha256-wBpjAHikC06uJEbjaQQffCZq1QjMDJ2XSm8AJcOfmLE=";
    };
    date = "2026-07-11";
  };
  lombok = {
    pname = "lombok";
    version = "1.18.46";
    src = fetchurl {
      url = "https://repo1.maven.org/maven2/org/projectlombok/lombok/1.18.46/lombok-1.18.46.jar";
      sha256 = "sha256-AfexoBXjPiti1fXzcFMwY1erFBX9GB/Lp3lPXRmMESY=";
    };
  };
  pint = {
    pname = "pint";
    version = "v0.87.0";
    src = fetchFromGitHub {
      owner = "cloudflare";
      repo = "pint";
      rev = "v0.87.0";
      fetchSubmodules = false;
      sha256 = "sha256-gQosR2LovEEw0AOzIf91AJAL2cMvygMEsYGszvSYFps=";
    };
  };
  tmux-mouse-swipe = {
    pname = "tmux-mouse-swipe";
    version = "8667851876c7591c668f29df6a142271051a3e2d";
    src = fetchFromGitHub {
      owner = "jaclu";
      repo = "tmux-mouse-swipe";
      rev = "8667851876c7591c668f29df6a142271051a3e2d";
      fetchSubmodules = false;
      sha256 = "sha256-0Mh0sQm3GP1V/KlYi6VjD3Zx2ssLwVI5uOnOp67trYk=";
    };
    date = "2025-12-29";
  };
  tmux-nerd-font-window-name = {
    pname = "tmux-nerd-font-window-name";
    version = "0af812a228e1b9f538b8d220c6c59d82d7228973";
    src = fetchFromGitHub {
      owner = "joshmedeski";
      repo = "tmux-nerd-font-window-name";
      rev = "0af812a228e1b9f538b8d220c6c59d82d7228973";
      fetchSubmodules = false;
      sha256 = "sha256-b6CQdN33hU5li/0LUOHMs7oN8ffVRVQlSf17Twhz2e8=";
    };
    date = "2026-04-10";
  };
  tmux-open-nvim = {
    pname = "tmux-open-nvim";
    version = "d140ac66e24f1cd26b68638da01a82717a1921bd";
    src = fetchFromGitHub {
      owner = "trevarj";
      repo = "tmux-open-nvim";
      rev = "d140ac66e24f1cd26b68638da01a82717a1921bd";
      fetchSubmodules = false;
      sha256 = "sha256-lftDhRERenGVDTWFP1o/bfZIk0RsHh2PxoYY8j8/9CQ=";
    };
    date = "2026-04-20";
  };
}
